# Generated by Django 5.2.12 on 2026-04-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_anonymouswin_book_remove_customuser_daily_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manual_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
